===== TABLE: TimesheetLines =====
Partition: TimesheetLines
Source Type: Microsoft.AnalysisServices.Tabular.MPartitionSource


Expression : let
                 Source = CommonDataService.Database(#"CDS_ENV"),
                 #"Query Selected Columns" = Value.NativeQuery(Source, "
             SELECT
               ts.tpg_timesheetid
             , ts.createdon
             , ts.modifiedon
             , ts.createdbyname
             , ts.modifiedbyname
             , ts.ownerid
             , ts.owneridname
             , ts.tpg_row
             --, ts.tpg_assignment
             , ts.tpg_comment
             , ts.tpg_onsitename
             , ts.tpg_total
             , ts.tpg_period
             ,gbl_submitterdepartment
             ,gbl_Submitterdepartmentid
             --, ts.tpg_planres
             , ts.tpg_project
             --, ts.tpg_planrestask
             --, ts.tpg_assignmentname
             , ts.tpg_periodname
             --, ts.tpg_planresname
             , ts.tpg_projectname
             --, ts.tpg_approver
             , ts.tpg_approvername
             --, ts.tpg_approverteam
             , ts.tpg_approverteamname
             , ts.tpg_approverscomment
             , ts.tpg_favouritename
             , ts.tpg_statusname
             , ts.tpg_submitter
             , ts.tpg_submittername
             , ts.tpg_task
             , ts.tpg_taskname
             , period.tpg_start AS [Period Start Date]
              FROM [dbo].[tpg_timesheet] AS ts
              LEFT JOIN [dbo].[tpg_period] AS period
              ON (ts.tpg_period = period.tpg_periodid)
              WHERE
              (ts.[statecodename] = 'Active')
              AND (ts.[tpg_periodname] IS NOT NULL)
             ", null, [EnableFolding = true]),
                 #"Changed Type" = Table.TransformColumnTypes(#"Query Selected Columns",{{"createdon", type date}, 
             {"modifiedon", type date}, {"Period Start Date", type date}, {"tpg_timesheetid", type text}, {"ownerid", 
             type text}, {"tpg_period", type text}, {"tpg_project", type text}, {"tpg_task", type text}, 
             {"tpg_submitter", type text}}),
                 #"Added TimesheetResourceUID" = Table.AddColumn(#"Changed Type", "TimesheetResourceUserUID", each if 
             [tpg_statusname] = null then [ownerid] else if [tpg_statusname] = "Draft" then [ownerid] else if 
             [tpg_statusname] <> "Draft" then [tpg_submitter] else null, type text),
                 #"Added TimesheetResourceName" = Table.AddColumn(#"Added TimesheetResourceUID", "Timesheet Resource 
             Name", each if [tpg_statusname] = null then [owneridname] else if [tpg_statusname] = "Draft" then 
             [owneridname] else if [tpg_statusname] <> "Draft" then [tpg_submittername] else null, type text),
                 #"Renamed Columns" = Table.RenameColumns(#"Added TimesheetResourceName",{{"tpg_timesheetid", 
             "TimesheetUID"}, {"createdon", "Created Date"}, {"modifiedon", "Modified Date"}, {"createdbyname", 
             "Created By"}, {"modifiedbyname", "Modified By"}, {"ownerid", "OwnerUID"}, {"owneridname", "Owner Name"}, 
             {"tpg_row", "TimesheetRowID"}, {"tpg_comment", "Comment"}, {"tpg_onsitename", "On Site"}, {"tpg_period", 
             "PeriodUID"}, {"tpg_project", "ProjectUID"}, {"tpg_periodname", "Period"}, {"tpg_projectname", "Project 
             Name"}, {"tpg_approvername", "Approver Name"}, {"tpg_approverteamname", "Approver Team Name"}, 
             {"tpg_approverscomment", "Approver Comment"}, {"tpg_favouritename", "Favourite"}, {"tpg_statusname", 
             "Timesheet Status"}, {"tpg_submittername", "Submitter Name"}, {"tpg_task", "TaskUID"}, {"tpg_taskname", 
             "Task Name"}, {"tpg_submitter", "SubmitterUID"}, {"tpg_total", "Period Total Hours"}})
             in
                 #"Renamed Columns"
Attributes : 
Partition  : Microsoft.AnalysisServices.Tabular.Partition




===== TABLE: Resources =====
Partition: Resources-6c5e788d-6586-4ba9-895a-380253a08acd
Source Type: Microsoft.AnalysisServices.Tabular.MPartitionSource


Expression : let
                 Source = CommonDataService.Database(#"CDS_ENV"),
                 #"Query Selected Columns" = Value.NativeQuery(Source, "select * from 
             tpg_resourcepool",null,[EnableFolding=true]),
                 #"Added Max Units" = Table.AddColumn(#"Query Selected Columns", "Max Units", each [tpg_maxunits] / 
             100),
                 #"Added URL" = Table.AddColumn(#"Added Max Units", "Resource URL", each "https://" & 
             Text.From(CDS_ENV) & "/main.aspx?appid=" & Text.From(APP_ID) & 
             "&pagetype=entityrecord&etn=tpg_resourcepool&id=" & Text.From([tpg_resourcepoolid])),
                 #"Replaced Value" = Table.ReplaceValue(#"Added URL",null,0,Replacer.ReplaceValue,{"tpg_standardrate", 
             "Max Units"}),
                 #"Removed Columns" = Table.RemoveColumns(#"Replaced Value",{"tpg_maxunits"}),
                 #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"tpg_standardrate", Currency.Type}, 
             {"Max Units", Percentage.Type}}),
                 #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"tpg_resourcepoolid", "ResourceID"}, 
             {"tpg_name", "ResourceName"}, {"statuscode", "StatusID"}, {"statuscodename", "Status"}, {"tpg_dept", 
             "DepartmentID"}, {"tpg_deptname", "Department"}, {"tpg_earliestavailability", "Earliest Available Date"}, 
             {"tpg_latestavailability", "Latest Available Date"}, {"tpg_resourcetype", "TypeID"}, 
             {"tpg_resourcetypename", "Type"}, {"transactioncurrencyid", "CurrencyID"}, {"transactioncurrencyidname", 
             "Currency"}, {"exchangerate", "Exchange Rate"}, {"tpg_standardrate", "Standard Rate"}, {"tpg_imageurl", 
             "Image URL"}})
             in
                 #"Renamed Columns"
Attributes : 
Partition  : Microsoft.AnalysisServices.Tabular.Partition




===== TABLE: TimesheetLineActuals =====
Partition: TimesheetLineActuals
Source Type: Microsoft.AnalysisServices.Tabular.MPartitionSource


Expression : let
                 Source = CommonDataService.Database(#"CDS_ENV"),
                 #"Query Selected Columns" = Value.NativeQuery(Source, "
             SELECT
               ts.[tpg_timesheetid] AS [TimesheetUID]
             , ts.[tpg_p01] AS [TS-Hours]
             , DATEADD(DAY, 0, period.[tpg_start]) AS [TimeByDay]
             , YEAR(DATEADD(DAY, 0, period.[tpg_start])) AS [TimeByDay Year]
             , MONTH(DATEADD(DAY, 0, period.[tpg_start])) AS [TimeByDay Month]
             --, FORMAT(DATEADD(DAY, 0, period.[tpg_start]), 'yyyyMM') AS [TimeByDay YYYYMM]
             , LEFT(DATENAME(MONTH, DATEADD(DAY, 0, period.[tpg_start])), 3) AS [TimeByDay Month Short]
             --, DATEPART(WEEK, DATEADD(DAY, 0, period.[tpg_start])) AS [TimeByDay Week]
             , DAY(DATEADD(DAY, 0, period.[tpg_start])) AS [TimeByDay Day]
              FROM [dbo].[tpg_timesheet] AS ts
              LEFT JOIN [dbo].[tpg_period] AS period
              ON (ts.tpg_period = period.tpg_periodid)
              WHERE (ts.[statecodename] = 'Active') AND (ts.[tpg_periodname] IS NOT NULL)
             --
             UNION ALL
             SELECT
               ts.[tpg_timesheetid] AS [TimesheetUID]
             , ts.[tpg_p02] AS [TS-Hours]
             , DATEADD(DAY, 1, period.[tpg_start]) AS [TimeByDay]
             , YEAR(DATEADD(DAY, 1, period.[tpg_start])) AS [TimeByDay Year]
             , MONTH(DATEADD(DAY, 1, period.[tpg_start])) AS [TimeByDay Month]
             --, FORMAT(DATEADD(DAY, 1, period.[tpg_start]), 'yyyyMM') AS [TimeByDay YYYYMM]
             , LEFT(DATENAME(MONTH, DATEADD(DAY, 1, period.[tpg_start])), 3) AS [TimeByDay Month Short]
             --, DATEPART(WEEK, DATEADD(DAY, 1, period.[tpg_start])) AS [TimeByDay Week]
             , DAY(DATEADD(DAY, 1, period.[tpg_start])) AS [TimeByDay Day]
              FROM [dbo].[tpg_timesheet] AS ts
              LEFT JOIN [dbo].[tpg_period] AS period
              ON (ts.tpg_period = period.tpg_periodid)
              WHERE (ts.[statecodename] = 'Active') AND (ts.[tpg_periodname] IS NOT NULL)
             --
             UNION ALL
             SELECT
               ts.[tpg_timesheetid] AS [TimesheetUID]
             , ts.[tpg_p03] AS [TS-Hours]
             , DATEADD(DAY, 2, period.[tpg_start]) AS [TimeByDay]
             , YEAR(DATEADD(DAY, 2, period.[tpg_start])) AS [TimeByDay Year]
             , MONTH(DATEADD(DAY, 2, period.[tpg_start])) AS [TimeByDay Month]
             --, FORMAT(DATEADD(DAY, 2, period.[tpg_start]), 'yyyyMM') AS [TimeByDay YYYYMM]
             , LEFT(DATENAME(MONTH, DATEADD(DAY, 2, period.[tpg_start])), 3) AS [TimeByDay Month Short]
             --, DATEPART(WEEK, DATEADD(DAY, 2, period.[tpg_start])) AS [TimeByDay Week]
             , DAY(DATEADD(DAY, 2, period.[tpg_start])) AS [TimeByDay Day]
              FROM [dbo].[tpg_timesheet] AS ts
              LEFT JOIN [dbo].[tpg_period] AS period
              ON (ts.tpg_period = period.tpg_periodid)
              WHERE (ts.[statecodename] = 'Active') AND (ts.[tpg_periodname] IS NOT NULL)
             --
             UNION ALL
             SELECT
               ts.[tpg_timesheetid] AS [TimesheetUID]
             , ts.[tpg_p04] AS [TS-Hours]
             , DATEADD(DAY, 3, period.[tpg_start]) AS [TimeByDay]
             , YEAR(DATEADD(DAY, 3, period.[tpg_start])) AS [TimeByDay Year]
             , MONTH(DATEADD(DAY, 3, period.[tpg_start])) AS [TimeByDay Month]
             --, FORMAT(DATEADD(DAY, 3, period.[tpg_start]), 'yyyyMM') AS [TimeByDay YYYYMM]
             , LEFT(DATENAME(MONTH, DATEADD(DAY, 3, period.[tpg_start])), 3) AS [TimeByDay Month Short]
             --, DATEPART(WEEK, DATEADD(DAY, 3, period.[tpg_start])) AS [TimeByDay Week]
             , DAY(DATEADD(DAY, 3, period.[tpg_start])) AS [TimeByDay Day]
              FROM [dbo].[tpg_timesheet] AS ts
              LEFT JOIN [dbo].[tpg_period] AS period
              ON (ts.tpg_period = period.tpg_periodid)
              WHERE (ts.[statecodename] = 'Active') AND (ts.[tpg_periodname] IS NOT NULL)
             --
             UNION ALL
             SELECT
               ts.[tpg_timesheetid] AS [TimesheetUID]
             , ts.[tpg_p05] AS [TS-Hours]
             , DATEADD(DAY, 4, period.[tpg_start]) AS [TimeByDay]
             , YEAR(DATEADD(DAY, 4, period.[tpg_start])) AS [TimeByDay Year]
             , MONTH(DATEADD(DAY, 4, period.[tpg_start])) AS [TimeByDay Month]
             --, FORMAT(DATEADD(DAY, 4, period.[tpg_start]), 'yyyyMM') AS [TimeByDay YYYYMM]
             , LEFT(DATENAME(MONTH, DATEADD(DAY, 4, period.[tpg_start])), 3) AS [TimeByDay Month Short]
             --, DATEPART(WEEK, DATEADD(DAY, 4, period.[tpg_start])) AS [TimeByDay Week]
             , DAY(DATEADD(DAY, 4, period.[tpg_start])) AS [TimeByDay Day]
              FROM [dbo].[tpg_timesheet] AS ts
              LEFT JOIN [dbo].[tpg_period] AS period
              ON (ts.tpg_period = period.tpg_periodid)
              WHERE (ts.[statecodename] = 'Active') AND (ts.[tpg_periodname] IS NOT NULL)
             --
             UNION ALL
             SELECT
               ts.[tpg_timesheetid] AS [TimesheetUID]
             , ts.[tpg_p06] AS [TS-Hours]
             , DATEADD(DAY, 5, period.[tpg_start]) AS [TimeByDay]
             , YEAR(DATEADD(DAY, 5, period.[tpg_start])) AS [TimeByDay Year]
             , MONTH(DATEADD(DAY, 5, period.[tpg_start])) AS [TimeByDay Month]
             --, FORMAT(DATEADD(DAY, 5, period.[tpg_start]), 'yyyyMM') AS [TimeByDay YYYYMM]
             , LEFT(DATENAME(MONTH, DATEADD(DAY, 5, period.[tpg_start])), 3) AS [TimeByDay Month Short]
             --, DATEPART(WEEK, DATEADD(DAY, 5, period.[tpg_start])) AS [TimeByDay Week]
             , DAY(DATEADD(DAY, 5, period.[tpg_start])) AS [TimeByDay Day]
              FROM [dbo].[tpg_timesheet] AS ts
              LEFT JOIN [dbo].[tpg_period] AS period
              ON (ts.tpg_period = period.tpg_periodid)
              WHERE (ts.[statecodename] = 'Active') AND (ts.[tpg_periodname] IS NOT NULL)
             --
             UNION ALL
             SELECT
               ts.[tpg_timesheetid] AS [TimesheetUID]
             , ts.[tpg_p07] AS [TS-Hours]
             , DATEADD(DAY, 6, period.[tpg_start]) AS [TimeByDay]
             , YEAR(DATEADD(DAY, 6, period.[tpg_start])) AS [TimeByDay Year]
             , MONTH(DATEADD(DAY, 6, period.[tpg_start])) AS [TimeByDay Month]
             --, FORMAT(DATEADD(DAY, 6, period.[tpg_start]), 'yyyyMM') AS [TimeByDay YYYYMM]
             , LEFT(DATENAME(MONTH, DATEADD(DAY, 6, period.[tpg_start])), 3) AS [TimeByDay Month Short]
             --, DATEPART(WEEK, DATEADD(DAY, 6, period.[tpg_start])) AS [TimeByDay Week]
             , DAY(DATEADD(DAY, 6, period.[tpg_start])) AS [TimeByDay Day]
              FROM [dbo].[tpg_timesheet] AS ts
              LEFT JOIN [dbo].[tpg_period] AS period
              ON (ts.tpg_period = period.tpg_periodid)
              WHERE (ts.[statecodename] = 'Active') AND (ts.[tpg_periodname] IS NOT NULL)
              ", null, [EnableFolding = true]),
                 #"Changed Type" = Table.TransformColumnTypes(#"Query Selected Columns",{{"TimeByDay", type date}})
             in
                 #"Changed Type"
Attributes : 
Partition  : Microsoft.AnalysisServices.Tabular.Partition




===== TABLE: Resource Demand =====
Partition: Resource Demand-e7e2f061-4fba-4034-86a1-fbc28c364af7
Source Type: Microsoft.AnalysisServices.Tabular.MPartitionSource


Expression : let
                 Source = tpg_capacitymwds,
             
                 #"Merged Resource Plan By Project" = Table.NestedJoin(
                     Source,
                     {"ResourceID", "DepartmentID", "Capacity Date"},
                     #"Resource Plan_GroupedForDemand",
                     {"ResourceID", "DepartmentID", "Resource Plan Date"},
                     "Resource Plan",
                     JoinKind.LeftOuter
                 ),
             
                 #"Expanded Resource Plan" = Table.ExpandTableColumn(
                     #"Merged Resource Plan By Project",
                     "Resource Plan",
                     {
                         "ProjectID",
                         "Project Name",
                         "AtossAbsent",
                         "Forecast Demand",
                         "ForecastDemandWithoutAtossAbsent"
                     },
                     {
                         "ProjectID",
                         "Project Name",
                         "AtossAbsent",
                         "Forecast Demand",
                         "ForecastDemandWithoutAtossAbsent"
                     }
                 ),
             
                 #"Replaced Null Forecast" = Table.ReplaceValue(
                     #"Expanded Resource Plan",
                     null,
                     0,
                     Replacer.ReplaceValue,
                     {"Forecast Demand", "AtossAbsent", "ForecastDemandWithoutAtossAbsent"}
                 ),
             
                 #"Added Availability" = Table.AddColumn(
                     #"Replaced Null Forecast",
                     "Availability",
                     each [Capacity] - ([Forecast Demand] / 8),
                     type number
                 ),
             
                 #"Merged Resources" = Table.NestedJoin(
                     #"Added Availability",
                     {"ResourceID"},
                     Resources,
                     {"ResourceID"},
                     "Resources",
                     JoinKind.LeftOuter
                 ),
             
                 #"Expanded Resources" = Table.ExpandTableColumn(
                     #"Merged Resources",
                     "Resources",
                     {"tpg_user"},
                     {"tpg_user"}
                 ),
             
                 #"Merged Timesheets By Project" = Table.NestedJoin(#"Expanded Resources", {"tpg_user", "Capacity 
             Date", "ProjectID"}, TimesheetLines_GroupedForDemand, {"TimesheetResourceUserUID", "Period Start Date", 
             "ProjectUID"}, "TimesheetLines", JoinKind.LeftOuter),
             
                 #"Expanded Timesheets" = Table.ExpandTableColumn(
                     #"Merged Timesheets By Project",
                     "TimesheetLines",
                     {"HoursTotal"},
                     {"Worked Hours"}
                 ),
             
                 #"Replaced Null Worked Hours" = Table.ReplaceValue(
                     #"Expanded Timesheets",
                     null,
                     0,
                     Replacer.ReplaceValue,
                     {"Worked Hours"}
                 )
             in
                 #"Replaced Null Worked Hours"
Attributes : 
Partition  : Microsoft.AnalysisServices.Tabular.Partition




