flowchart LR
  sales_all_customer_sales["All Customer Sales"]
  sales_refresh_sensitive_sales["Refresh Sensitive Sales"]
  sales_total_sales["Total Sales"]
  sales_sales_yoy_pct["Sales YoY %"]
  sales_total_sales_prior_year["Total Sales Prior Year"]
  sales_all_customer_sales --> sales_total_sales
  sales_refresh_sensitive_sales --> sales_total_sales
  sales_sales_yoy_pct --> sales_total_sales
  sales_sales_yoy_pct --> sales_total_sales_prior_year
  sales_total_sales_prior_year --> sales_total_sales

